language: erlang
otp_release:
  - R16B
script: make test

install:
  - URL='http://aphyr.com/riemann/riemann_0.2.4_all.deb'; FILE=`mktemp`; DEBIAN_FRONTEND=noninteractive; wget "$URL" -qO $FILE && sudo dpkg -i $FILE; rm $FILE
before_script:
  - sudo service riemann start
